### ISSUE TITLE
Check genetic relatedness of all samples from BSSNPer and RNASeq SNP calling

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#11]

**Comment by hputnam** [comment]
@daniellembecker is this complete? Can you please add the link to the scripts here and close if complete?

**Comment by daniellembecker** [comment]
Yes this is complete! 

For RNASeq SNP calling, can be found at end of workflow here where BCFtools and SAMtools was used for SNP calling and PLINK was used for calculating genetic relatedness :
[Workflow here](https://github.com/daniellembecker/DanielleBecker_Lab_Notebook/blob/master/_posts/2022-12-10-P.verrucosa-RNASeq-Workflow-Host.md)

Then, I visualized the pairwise comparisons of genetic relatedness [here](https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/genetic_relatedness.Rmd):

Created a heatmap showing that the relatedness values we have between our samples (all < 0 besides the 1:1 relationship between individual samples to each other) indicating our samples have relatively distinct genotypes compared to what would be expected under a model of random mating within a single population.

<img width="1429" alt="Screen Shot 2024-08-13 at 10 48 15 AM" src="https://github.com/user-attachments/assets/ba1739a7-ed19-42d7-8ba0-ba1d03c3cc32">

For WGBS, [here is the workflow](https://github.com/daniellembecker/DanielleBecker_Lab_Notebook/blob/master/_posts/2024-02-12-BS-SNPer-Molec-Underpinnings-WGBS.md) and calculations also using PLINK after BS-snper calling.

I am currently re-running because I re-ran BS-snper with only the 29 samples and not 32 but was giving a similar story.
