### ISSUE TITLE
Clarify the Annotation file

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#13]
This file needs to have 27,439 genes to match all in the genome paper, even if genes did not have any hits

**Comment by daniellembecker** [comment]
Look into creating of pver_GOterms_interprot_swissprot_blast_trembl_20211203.csv file to see why genes aren't matching full annot file

**Comment by daniellembecker** [comment]
https://github.com/hputnam/Becker_E5/blob/master/Functional_Annotation/Scripts/pver_annot_compile.Rmd

**Comment by daniellembecker** [comment]
https://github.com/hputnam/Becker_E5/blob/master/Functional_Annotation/2021-12-08-Molecular-Underpinnings-Functional-Annotation-Pipeline.md

**Comment by daniellembecker** [comment]
Solved why the pver_GOterms_interprot_swissprot_blast_trembl_20211203.csv file had less then 27,439 genes, it was due to NA filtering in the https://github.com/hputnam/Becker_E5/blob/master/Functional_Annotation/Scripts/pver_annot_compile.Rmd script, I have now commented out the na.omits from the script. However, there are still inconsistent gene naming issues I am addressing in issue #14
