### ISSUE TITLE
Describe assembly stats in workflow to show reasons for what was done

### ISSUE THREAD

**Issue by hputnam** [hputnam/Becker_E5#4]
https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md for step 7 c, d, and e

**Comment by hputnam** [comment]
Same for the symbiont workflow: https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow_SymbiontC1.md

**Comment by daniellembecker** [comment]
Updated by adding the stats output  for assembly quality:  

For https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow.md
cd /data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/counts/merged.stats 

For https://github.com/hputnam/Becker_E5/blob/master/Bioinformatics/Workflows/P.verrucosa_RNASeq_Workflow_SymbiontC1.md
cd /data/putnamlab/dbecks/Becker_E5/Becker_RNASeq/data/counts_C1/merged.stats

**Comment by hputnam** [comment]
Why do we need to do the merge? Isn't it redundant if you first use -e and -G?

**Comment by daniellembecker** [comment]
I was looking into this further and it does seem redundant, it is recommended as a step after assessing the quality because: "Once you have assessed the quality of your assembly, re-estimating transcript abundances using the latest reference annotations ensures that your quantifications are as accurate as possible."

So it is helpful if a reference is being updated or has been changed since last running the assembly. So while it is redundant, doesn't cause any issues and more a sanity check if the reference is changed, not applicable in our case though.

**Comment by hputnam** [comment]
It is redundant because there is no need to re-estimate anything because you used -e and -G. The re-estimation is only for if you did not use the -e and you generated novel transcripts that then are reported in the gft and need to be merged into the new gtf.

**Comment by daniellembecker** [comment]
@hputnam since this step was redundant should I remove and redo or it doesn't change anything downstream so should I keep?

**Comment by hputnam** [comment]
You can keep it. Just comment it in the code with the logic/information so people can understand what the gffcompare tells you
